[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
arbitrage_program = "33BQPv9UU9moaQPah9umUad4ovijbF2TVmxcGdSmeSJR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

timeout = 120

[scripts]
test = "mocha -t 1000000 tests/"
